[package]
name = "fltk-egui"
version = "0.2.1"
edition = "2018"
authors = ["MoAlyousef <mohammed.alyousef@neurosrg.com>"]
description = "FLTK backend for egui"
repository = "https://github.com/fltk-rs/fltk-egui"
documentation = "https://docs.rs/fltk-egui"
keywords = ["gui", "widgets", "graphics"]
categories = ["gui"]
readme = "README.md"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = { version = "1", features = ["enable-glwindow"] }
gl = "0.14"
egui = "0.14"

[dependencies.copypasta]
version = "0.7"
optional = true

[features]
clipboard = ["copypasta"]

[dev-dependencies]
egui_demo_lib = "0.14"
