[package]
name = "fltk-egui"
version = "0.6.0"
edition = "2021"
authors = ["MoAlyousef <mohammed.alyousef@neurosrg.com>", "Adia Robbie <adyaro37@gmail.com>"]
description = "FLTK backend for egui"
repository = "https://github.com/fltk-rs/fltk-egui"
documentation = "https://docs.rs/fltk-egui"
keywords = ["gui", "widgets", "graphics"]
categories = ["gui"]
readme = "README.md"
license = "MIT"
rust-version = "1.56"

[dependencies]
epi = "0.17"
egui_glow = { version = "0.17", default-features = false, features = [
    "default_fonts",
] }
egui_extras = { version = "0.17", default-features = false }

# for internal use case faster build (bundled).
# fltk = { version = "1.3", features = ["enable-glwindow", "fltk-bundled"] }
fltk = { version = "1.3", features = ["enable-glwindow"] }

# for the demo_windows example
[dev-dependencies]
egui_demo_lib = "0.17"

# clipboard dep
[target."cfg(windows)".dependencies.copypasta]
version = "0.7"
optional = true

[target."cfg(all(unix, not(any(target_os=\"linux\", target_os=\"freebsd\"))))".dependencies.copypasta]
version = "0.7"
optional = true

[target."cfg(all(unix, any(target_os=\"linux\", target_os=\"freebsd\")))".dependencies.copypasta]
version = "0.7"
optional = true
default-features = false

[features]
default = ["x11"]
x11 = ["copypasta/x11"]
wayland = ["copypasta/wayland", "fltk/use-wayland"]
fltk-bundled = ["fltk/fltk-bundled"]
no-pango = ["fltk/no-pango"]
