[package]
name = "fltk-egui"
version = "0.3.3"
edition = "2018"
authors = ["MoAlyousef <mohammed.alyousef@neurosrg.com>"]
description = "FLTK backend for egui"
repository = "https://github.com/fltk-rs/fltk-egui"
documentation = "https://docs.rs/fltk-egui"
keywords = ["gui", "widgets", "graphics"]
categories = ["gui"]
readme = "README.md"
license = "MIT"

[dependencies]
fltk = { version = "1.2.5", features = ["enable-glwindow"] }
gl = "0.14"
egui = "0.14"

# for the demo_windows example
[dev-dependencies]
egui_demo_lib = "0.14"

[features]
fltk-bundled = ["fltk/fltk-bundled"]
no-pango = ["fltk/no-pango"]